### ISSUE TITLE
Redis store does not work?

### ISSUE THREAD

**Issue by furiousassault** [EagleChen/restrictor#1]
Good day. First of all, thank you for your project. 

It seems that example from Readme does not work with Redis. Would it be difficult to fix it?

**Comment by EagleChen** [comment]
Could you provide more information?

[`NewRedisStore`](https://github.com/EagleChen/restrictor/blob/master/store.go#L153) needs some parameters. Have you correctly set them?

@furiousassault

**Comment by furiousassault** [comment]
@EagleChen thanks for the response.
Well, I didn't. Trying to do something naive like that for starters:
```
main() {
	store, err := restrictor.NewRedisStore("redis://localhost:6379" )
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	r := restrictor.NewRestrictor(1*time.Minute, 2, 60, store)

	for i:=0; i<15; i++ {
		if r.LimitReached("somekey") {
			fmt.Println("reached")
		} else {
			fmt.Println("ok")
		}
	}
}
```
It produces only ok, which is not expected.
Using redis:5.0.3-stretch.
I see that keys appear in redis, so I thought that's not a connectivity issues.
Could you please describe what options must be set? Have no clue.

**Comment by EagleChen** [comment]
I will fix it later

**Comment by EagleChen** [comment]
@furiousassault I've updated this repo. You can have a try using the latest code

**Comment by furiousassault** [comment]
Seems like the basic problem has been solved, thank you. At least, the sample above works as expected now. I think issue can be closed.
